name: 'Create New GCP Sandbox Proiect!'

on:
  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        required: true 
        type: string 
        description: Project Name

permissions:
  id-token: write 
  contents: write

jobs:
  setup_new_directory:
    runs-on: ubuntu-20.04
    outputs:
      mybranch: ${{ steps.get_branch_name.outputs.project }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install required tools 
      run: |-
        sudo apt-get install -y gettext-base
        sudo apt-get install moreutils
        sudo apt-get update -y 
        sudo apt-get --yes install openssh-client
        
    - name: Authenticating gcloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_NEW }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Use gcloud CLI'
      run: |
        gcloud info
        
    - name: Create BRANCH NAME env variable 
      run: echo "BRANCH_NAME=feature/${{github.event.inputs.PROJECT_NAME}}" >> $GITHUB_ENV
          
    - name: Read BRANCH NAME env variable
      id: get_branch_name
      run: 
        echo "${{ env.BRANCH_NAME }}"
        echo "project=${{github.event.inputs.PROJECT_NAME}}" >> $GITHUB_OUTPUT

    - name: Checkout new or existing branch 
      run: |-
        if [ $(git branch -a | grep "${{ env.BRANCH_NAME }}" | wc -l) -eq 0 ]; then git branch "${{ env.BRANCH_NAME }}" && echo "branch created"; fi
        git checkout ${{ env.BRANCH_NAME }}
        git config --global user.email ${{env.GIT_COMMITTER_EMAIL}}
        git config --global user.name  ${{env.GIT_COMMITTER_NAME}}
      env:
        GIT AUTHOR EMAIL: "git@github.com"
        GIT_AUTHOR_NAME: "Github Actions"
        GIT_COMMITTER_EMAIL: "git@github.com"
        GIT_COMMITTER_NAME: "Github Actions"
    - name: Add Subscription Project 
      run: |-
        ls
        if [ -d ${{github.event.inputs.PROJECT_NAME}} ]; then 
          echo "Directory already exists, skipping creation."
          cd ${{github.event.inputs.PROJECT_NAME}}
          if [ -e ${{github.event.inputs.PROJECT_NAME}}-data.json ]; then
            echo "File exists reconcilling with any commits done to the json file and changes made in the cloud"
            python3 main.py
            rm -rf gha-creds-*.json
            if ! diff ${{github.event.inputs.PROJECT_NAME}}-data.json <(git show HEAD:./${{github.event.inputs.PROJECT_NAME}}-data.json) >/dev/null ; then
              git add ${{github.event.inputs.PROJECT_NAME}}-data.json 
              git commit -m "new json file"
              git push -u origin "${{env.BRANCH_NAME}}"
            else
              echo "No changes to data.json file No need to for plan and apply in terraform"
            fi
          else
            echo "Creation new json file"
            python3 main.py
            rm -rf gha-creds-*.json
            if ! diff ${{github.event.inputs.PROJECT_NAME}}-data.json <(git show HEAD:./${{github.event.inputs.PROJECT_NAME}}-data.json) >/dev/null ; then
              git add ${{github.event.inputs.PROJECT_NAME}}-data.json 
              git commit -m "new json file"
              git push -u origin "${{env.BRANCH_NAME}}"
            else
              echo "No changes to data.json file"
            fi
          fi 
        else 
          mkdir -p ${{github.event.inputs.PROJECT_NAME}} \
          && echo "Directory created, copying files." \
          && cp template/* ${{github.event.inputs.PROJECT_NAME}} \
          && cd ${{github.event.inputs.PROJECT_NAME}} \
          && envsubst < "main.py" | sponge "main.py" \
          && envsubst < "backend.tf" | sponge "backend.tf" \
          && envsubst < terraform.tfvars.template > terraform.auto.tfvars \
          && python3 main.py
        fi
      env:
        PROJECT_NAME: ${{github.event.inputs.PROJECT_NAME}} 
        AD_GROUP_NAME : ${{github.event.inputs.AD_GROUP_NAME}} 
        COSTCENTER: ${{github.event.inputs.COSTCENTER}} 
        OWNER: ${{github.event.inputs.OWNER}} 
        OWNER_EMAIL: ${{github.event.inputs.OWNER_EMAIL}} 
        ITPR: S{{github.event.inputs.ITPR}}
        CONTACT_EMAIL: ${{github.event.inputs.CONTACT_EMAIL}}
        DATACLASS: ${{github.event.inputs.DATACLASS}} 
        APPNAME: ${{github.event.inputs.APPNAME}}

    - name: Add, Commit, and Push Changes
      run: |-
        ls
        rm -rf gha-creds-*.json
        git add .
        if git diff-index --quiet HEAD --; then
           echo "No changes to commit"
        else
          git commit -m "Added ${{github.event.inputs.PROJECT_NAME}} sandbox project" 
          git push -u origin "${{env.BRANCH_NAME}}" 
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GIT_AUTHOR_EMAIL: "git@github.com"
        GIT_AUTHOR_NAME: "Github Actions"
        GIT_COMMITTER_EMAIL: "git@github.com"
        GIT_COMMITTER_NAME: "Github Actions"
        
  gcp_validation_and_plan:
    runs-on: ubuntu-latest
    needs: setup_new_directory
    steps:
    - run: echo ${{needs.setup_new_directory.outputs.mybranch}} 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
        ref: feature/${{needs.setup_new_directory.outputs.mybranch}}
    - name: 'Install required tools'
      run: |-
        uname -a
        curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
        chmod +x envsubst
        sudo mv envsubst /usr/local/bin
        sudo apt-get update -y
        sudo apt-get --yes install openssh-client
        type ssh-keyscan
        sudo apt-get install -y nodejs
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1    
    - name: Authenticating gcloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_NEW }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Use gcloud CLI'
      run: |
        gcloud info               
    - id: terraform_init
      name: 'Initialize Terraform'
      working-directory: ${{ needs.setup_new_directory.outputs.mybranch }}
      run: terraform init
    - id: terraform_plan
      name: 'Plan Terraform'
      working-directory: ${{ needs.setup_new_directory.outputs.mybranch }}
      run: 
       terraform plan 
        
