name: Terraform Plan

# on:
#  workflow_run:
#     workflows: ["Create New GCP Sandbox Proiect!"]
#     types: 
#       - completed


permissions:
  id-token: write
  contents: write
      
jobs:
  get-projects:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
        ref: 'feature/new-project2-376506'

    - name: debug list directories
      run: |
        git diff --name-only  origin/main 
        git diff --name-only  origin/main | grep -E '.*\.(tf|tfvars)$' | awk -F '/' '{print $1}' | uniq | jq -cnR '[inputs | select(length>0)]'
        pwd
        ls
    
    - id: list_dirs
      run: |
        echo "::set-output name=matrix::$(git diff --name-only  origin/main | grep -E '.*\.(tf|tfvars)$' | awk -F '/' '{print $1}' | uniq | jq -cnR '[inputs | select(length>0)]')"
      
 
  gcp_validation_and_plan:
    runs-on: ubuntu-latest
    needs: get-projects
    if: ${{ needs.get-projects.outputs.matrix != '[]' && needs.get-projects.outputs.matrix != '' }}
    strategy:
      matrix:
        subdir: ${{fromJson(needs.get-projects.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
        ref: 'feature/new-project2-376506'

    - name: 'Install required tools'
      run: |-
        uname -a
        curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
        chmod +x envsubst
        sudo mv envsubst /usr/local/bin
        sudo apt-get update -y
        sudo apt-get --yes install openssh-client
        type ssh-keyscan
        sudo apt-get install -y nodejs
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      
    - name: Authenticating gcloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_NEW }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Use gcloud CLI'
      run: |
        gcloud info
        export CLOUDSDK_CORE_PROJECT=${{matrix.subdir}}
        gcloud config set project ${{matrix.subdir}}
        gsutil mb -l us-central1 gs://${{matrix.subdir}}_state_file_iam_roles/
    - name: Run python file to get all the principles
      run: |
          cd ${{matrix.subdir}}
          ls
          python3 main.py                  
    - id: terraform_init
      name: 'Initialize Terraform'
      working-directory: ${{matrix.subdir}}
      run: terraform init
    - id: terraform_plan
      name: 'Plan Terraform'
      working-directory: ${{matrix.subdir}}
      run: 
       terraform plan -o tfplan.out
       cat tfplan.out
      
     
    
      
    




















